#!/bin/bash
# Demo script for pcode interactive mode

echo "🤖 pcode Interactive Mode Demo"
echo "=============================="
echo ""
echo "pcode now supports interactive chat mode similar to Claude!"
echo ""
echo "To start interactive mode, simply run:"
echo "  ./target/release/pcode"
echo ""
echo "Or explicitly:"
echo "  ./target/release/pcode --interactive"
echo ""
echo "Available commands in interactive mode:"
echo "  help                    - Show help"
echo "  tools                   - List available tools"
echo "  /file_read <path>       - Read a file"
echo "  /file_write <path> <content> - Write to a file"
echo "  /process <command>      - Execute a command"
echo "  /llm <prompt>           - Query LLM (requires AI_STUDIO_API_KEY)"
echo "  /token_estimate <text>  - Estimate tokens"
echo "  clear                   - Clear screen"
echo "  exit                    - Exit"
echo ""
echo "Try it now!"